server:
  port: 9002

spring:
  application:
    name: nacos-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: LZLlzl12345
  cloud:
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8848
        server-addr: 192.168.43.122:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.liang.springcloud.entities
