server:
  port: 9003

spring:
  application:
    name: nacos-consumer-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: LZLlzl12345
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

service-url:
  nacos-user-service: http://nacos-provider-payment

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.liang.springcloud.entities
